version: "3.8"

services:
  nginx:
    image: "public.ecr.aws/nginx/nginx"
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./web-server/src/conf.d:/etc/nginx/conf.d:ro
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /home/vscode/app
    volumes:
      - ./frontend:/home/vscode/app:rw
    command: >
      sh -c "npm install && npm run dev"
    user: 1000:1000
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app:rw
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: >
      sh -c "uvicorn main:app --reload --host=0.0.0.0"
    user: 1000:1000
    depends_on:
      - db
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_volume:
