FROM python:3.9.17-slim-bullseye

COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# RUN pip install jwtauth --index-url https://__token__:YriP1ee8xHVf6--B4g4x@gitlab.com/api/v4/projects/26299275/packages/pypi/simple
